### PR TITLE
fMRIVolume related pull request w/ slice timing correction, registration to T1 and choice of preregistration tool

### PR DESCRIPTION
**Pull request by sivcek**
Created a single Pull Request with Slice timing functionality, T1 registration and a choice of preregistration tool.

### CODE REVIEW

**Comment by sivcek** [comment]
@glasserm @mharms @coalsont 
Can you just confirm that for these functionalities that have been approved by the individual PRs (it is merged PR <https://github.com/Washington-University/HCPpipelines/pull/139>, PR <https://github.com/Washington-University/HCPpipelines/pull/143>, and PR <https://github.com/Washington-University/HCPpipelines/pull/142>)
we are good to go?

**Comment by mharms** [comment]
At this point, I'm waiting for all the individual PRs to get finalized and merged into a single 'fMRIVolume' PR, at which point I figure we can review that PR for coherence and consistency.

**Comment by sivcek** [comment]
Deal. The clean implementation of PR <https://github.com/Washington-University/HCPpipelines/pull/144> I'll be testing tonight. Tuesday / wednesday we should have the results of testing the effects of nonlinear registration for PR <https://github.com/Washington-University/HCPpipelines/pull/147>.

**Comment by sivcek** [comment]
Joined with other PR into <https://github.com/Washington-University/HCPpipelines/pull/156>

**Pull request closed without merging**
