### PR TITLE
Unified fieldmap

### PR DESCRIPTION
**Pull request by axkralj990**
Hi,

This pull request improves the performance of the distortion correction for Philips B0 map fieldmap scans, by taking the echo difference (deltaTE) into account when computing the fieldmaps. We have also included phase unwrapping and image de-meaning. We followed exactly the same steps as are implemented in the fsl_prepare_fieldmap function for Siemens scanners. The only difference is the additional brain mask erosion step for Philips scans, which results in a cleaner preprocessed fieldmap. A comparison between the current Philips and Siemens steps for fieldmap preparation is shown on the attached figure.
The code has been tested successfully on both structural and functional images from Siemens and Philips scanners. It does not change any other parts of the processing pipelines.

With kind regards,

Grega & Aleksij

Fieldmaps

### CODE REVIEW

**Review by glasserm — COMMENTED** [review]
This seems to have conflicts with master.  Please resolve so that this can be merged.  Thanks.

**Comment by sivcek** [comment]
@glasserm `master` has been pulled into the `unified_fieldmap` feature branch and all conflicts resolved. Also, GitHub reports "This branch has no conflicts with the base branch. Merging can be performed automatically." The latest `master` change that the PR includes was committed on Aug. 25, by @coalsont, "update version.txt".

**Comment by glasserm** [comment]
I get this message "This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch."  We may need @coalsont to weigh in on how to fix.

**Comment by sivcek** [comment]
@glasserm How about a regular merge?

**Comment by glasserm** [comment]
Tim has asked that we do rebase and merge, so I'd like his input at this point.

**Comment by mharms** [comment]
Why the need for the "erode" step specifically in the Philips case?  I wonder if Oxford will want to include that in `fsl_prepare_fieldmap` if it isn't part of the processing for the other platforms...

**Comment by axkralj990** [comment]
I included the erode step for Philips data, since `fsl_prepare_fieldmap` function calls an additional internal function `clean_up_edge()` on Siemens data, which reduces the noise at the outer edge of the masked fieldmap image. I followed a recommendation to make the brain mask tighter by excluding the outermost edge of the fieldmap, which usually contains some noise. I've compared a preprocessed Philips B0 map with the modified `fsl_prepare_fieldmap` function, where `clean_up_edge()` is called, to a preprocessed scan with an eroded brain mask, and it looks like the former still contained some noise at the rim, despite calling `clean_up_edge()`. Because the code from this pull request does not have `clean_up_edge()` functionality and the scans seem to contain quite some noise at the rim, I decided to leave the erosion step in.

**Comment by mharms** [comment]
@axkralj990 Makes sense.  Thanks for the explanation.

**Comment by coalsont** [comment]
> Tim has asked that we do rebase and merge, so I'd like his input at this point.

Looks like he pulled the master with a merge commit to resolve conflicts, after all his changes, instead of doing a rebase.  I'll look at what the conflicts would be for a rebase.

**Comment by coalsont** [comment]
Looks like the philips_fieldmap branch this is based on has pulled from master multiple times, so this is problematic to convert to a rebase.  We can do this as a normal merge, but I would prefer that branches intended to become pull requests be rebased on master when you want to catch up, and avoid ever doing a pull merge from master.

**Comment by glasserm** [comment]
@coalsont and @mharms if there is no other review needed, I'm fine with Tim merging this.

**Comment by mharms** [comment]
I'm not planning on any further review.

**Comment by coalsont** [comment]
This is only intended to be in a future 4.3.1 release, right?  I haven't had confirmation of the current 4.3.0 candidate completing whatever testing is needed before making it the official release.

**Comment by mharms** [comment]
Yes. So, we'll need to update `version.txt`.

**Pull request merged**
