### PR TITLE
BUG: fixes b-value & gradient orientation for the selected b0

### PR DESCRIPTION
**Pull request by MichielCottaar**
This fixes a bug I previously introduced in the code base. When extracting the b-value/gradient orientation from the best b0, best_b0_pos_index gives the index out of all b0's, but this index is used on the full bvals/bvecs. This patch creates a bvals/bvecs for only the Pos b0 values and then uses best_b0_pos_index to extract the correct b0.

### CODE REVIEW

**Comment by glasserm** [comment]
Seems fine to me.  I presume we need to incorporate this before running diffusion preprocessing for lifespan?

**Comment by mharms** [comment]
Yes.  Maybe we can incorporate this on top of 6c33037, and tag as `v4.3.0-rc.2`?

**Comment by coalsont** [comment]
I will do that.

**Comment by coalsont** [comment]
Not sure why it didn't have the rebase option selected, I can fix that though.

**Comment by coalsont** [comment]
Tag v4.3.0-rc.2 (which does not contain any other changes to master after v4.3.0-rc.1) now exists, and the merge has been modified to be a rebase.

**Pull request merged**
